# Generated by Django 4.2.6 on 2023-10-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_courses_video_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(max_length=40),
        ),
        migrations.AlterField(
            model_name='courses',
            name='subtitle',
            field=models.TextField(max_length=20),
        ),
    ]
