# Generated by Django 4.2.6 on 2023-10-29 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_courses_description_alter_courses_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='courses',
            name='subtitle',
            field=models.TextField(max_length=10),
        ),
    ]
